services:
  - type: web
    name: gitagpt-api
    env: python
    runtime: python3.9.18
    buildCommand: |
      python3.9 -m pip install --upgrade pip==23.0.1
      python3.9 -m pip install setuptools==65.5.1 wheel==0.38.4
      python3.9 -m pip install torch==1.13.1 --index-url https://download.pytorch.org/whl/cpu
      python3.9 -m pip install -r requirements.txt
      python3.9 etl.py
    startCommand: python3.9 -m uvicorn api:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 75
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: chroma-data
      mountPath: /opt/render/project/src/chroma_db
      sizeGB: 1 