services:
  - type: web
    name: gitagpt-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: chroma-data
      mountPath: /app/chroma_db
      sizeGB: 1 